rvm:
- "2.2.1"
language: ruby
env:
- develpoment
before_install: gem install bundler
script:
- bundle install  
- RAILS_ENV=development bundle exec RAIS_ENV=rake db:create
- RAILS_ENV=development bundle exec rake db:migrate --trace





